### ISSUE TITLE
- no devices are being discovered or listed in the console of the editor. 

### ISSUE THREAD

**Issue by SpaceBug199** [fuziki/UnityCoreBluetooth#29]
Tested the plugin on one Mac mini (2018) with macOS 12.0.1 and on two MBP (2018) with macOS 10.15.7 and 12.1. 

- I was getting error: ....bundle” is damaged and can’t be opened

> Error is solved after the solution:
1. Open the MacOS terminal.
2. Enter the command: xattr -d com.apple.quarantine /.../Assets/Plugins/Whatever.bundle
3. Do this for every .bundle you have, and they once again work.
4. (Original link [https://forum.unity.com/threads/plugin-bundle-is-damaged-and-cant-be-opened-after-latest-macos-update.910004/](https://forum.unity.com/threads/plugin-bundle-is-damaged-and-cant-be-opened-after-latest-macos-update.910004/))

-Plugin starts fine after the fix. The example starts and gets to start Scan method. 
- no devices are being discovered or listed in the console. 

All of BLE devices have been identified with Bluetility app form all Mac computers (BLE works)

**Comment by fuziki** [comment]
Thanks for asking.
I think your method may not have loaded the plugin correctly.
Open the UnityCoreBluetooth.xcworkspace and try to build mcUnityCoreBluetooth.bundle in your environment.
