### ISSUE TITLE
Does it support Unity Editor on M1 OSX?

### ISSUE THREAD

**Issue by maowu** [fuziki/UnityCoreBluetooth#31]
I got this "DllNotFoundException: mcUnityCoreBluetooth assembly:<unknown assembly> type:<unknown type> member:(null)"
When I run on M1 OSX.

Unity version: 2022.2.19f1(silicon)
Mac OS: 12.4

**Comment by fuziki** [comment]
Run this↓ command and replace the built bundle

```
make bundle
```

**Comment by Damenspike** [comment]
Please will you provide a .bundle which supports M1? If not a little more on how to build it ourselves? Not an expert here.
